-- EDValleDigital - cierre de backend para RF01-RF08.
-- Idempotente: puede ejecutarse varias veces sin borrar pedidos ni productos.

alter table public.pedidos
  add column if not exists estado_pago text not null default 'pendiente',
  add column if not exists pago_confirmado boolean not null default false,
  add column if not exists fecha_confirmacion_pago timestamptz,
  add column if not exists usuario_caja_id uuid references auth.users(id),
  add column if not exists metodo_pago text,
  add column if not exists monto_pagado numeric(10, 2);

alter table public.pedido_items
  add column if not exists observacion_item text;

update public.estados_pedido set orden_flujo = 7 where estado_id = 'cancelado';
update public.estados_pedido set orden_flujo = 6 where estado_id = 'cerrado';

insert into public.estados_pedido (
  estado_id, nombre_estado, descripcion, orden_flujo, es_final
)
values ('entregado', 'entregado', 'Pedido entregado a la mesa y pendiente de cobro', 5, false)
on conflict (estado_id) do update
set nombre_estado = excluded.nombre_estado,
    descripcion = excluded.descripcion,
    orden_flujo = excluded.orden_flujo,
    es_final = excluded.es_final,
    updated_at = now();

alter table public.pedidos drop constraint if exists pedidos_estado_check;
alter table public.pedidos
  add constraint pedidos_estado_check
  check (estado in ('pendiente', 'recibido', 'en_preparacion', 'listo', 'entregado', 'cerrado', 'cancelado'));

alter table public.pedidos drop constraint if exists pedidos_estado_pago_check;
alter table public.pedidos
  add constraint pedidos_estado_pago_check
  check (estado_pago in ('pendiente', 'pagado', 'confirmado', 'anulado'));

create table if not exists public.historial_estados (
  historial_id bigint generated by default as identity primary key,
  pedido_codigo text not null references public.pedidos(codigo) on delete cascade,
  estado_id text,
  estado text not null,
  usuario_id uuid references auth.users(id),
  fecha_cambio timestamptz not null default now(),
  observacion text
);

create index if not exists historial_estados_pedido_idx
  on public.historial_estados(pedido_codigo, fecha_cambio desc);

create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select rol from public.perfiles where id = auth.uid()
$$;

create or replace function public.registrar_pedido_publico(
  p_codigo text,
  p_mesa text,
  p_nombre_cliente text,
  p_observacion text,
  p_items jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_total numeric(10, 2);
  v_items jsonb;
begin
  if coalesce(trim(p_codigo), '') = '' or coalesce(trim(p_mesa), '') = '' or coalesce(trim(p_nombre_cliente), '') = '' then
    raise exception 'Codigo, mesa y cliente son obligatorios';
  end if;

  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'El pedido debe incluir al menos un producto';
  end if;

  if exists (select 1 from public.pedidos where codigo = p_codigo) then
    raise exception 'El codigo del pedido ya existe';
  end if;

  with requested as (
    select
      item->>'producto_id' as producto_id,
      greatest(1, least(50, coalesce((item->>'cantidad')::integer, 1))) as cantidad,
      nullif(trim(item->>'observacion_item'), '') as observacion_item
    from jsonb_array_elements(p_items) item
  ), valid_items as (
    select
      p.id as producto_id,
      p.nombre,
      r.cantidad,
      p.precio as precio_unitario,
      round(p.precio * r.cantidad, 2) as subtotal,
      coalesce(r.observacion_item, '') as observacion_item
    from requested r
    join public.productos p on p.id = r.producto_id
    where p.disponible = true
  )
  select
    coalesce(sum(subtotal), 0),
    coalesce(jsonb_agg(to_jsonb(valid_items)), '[]'::jsonb)
  into v_total, v_items
  from valid_items;

  if jsonb_array_length(v_items) <> jsonb_array_length(p_items) then
    raise exception 'Uno o mas productos no existen o no estan disponibles';
  end if;

  insert into public.pedidos (codigo, estado, estado_id, fecha_hora, mesa, nombre_cliente, observacion, total)
  values (p_codigo, 'pendiente', 'pendiente', now(), trim(p_mesa), trim(p_nombre_cliente), coalesce(trim(p_observacion), ''), v_total);

  insert into public.pedido_items (
    pedido_codigo, producto_id, nombre, cantidad, precio_unitario, subtotal, observacion_item
  )
  select
    p_codigo,
    item->>'producto_id',
    item->>'nombre',
    (item->>'cantidad')::integer,
    (item->>'precio_unitario')::numeric,
    (item->>'subtotal')::numeric,
    item->>'observacion_item'
  from jsonb_array_elements(v_items) item;

  return public.consultar_pedido_publico(p_codigo);
end;
$$;

create or replace function public.consultar_pedido_publico(p_codigo text)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select to_jsonb(p) || jsonb_build_object(
    'items', coalesce((
      select jsonb_agg(to_jsonb(i) order by i.id)
      from public.pedido_items i
      where i.pedido_codigo = p.codigo
    ), '[]'::jsonb)
  )
  from public.pedidos p
  where p.codigo = p_codigo
$$;

create or replace function public.modificar_pedido_pendiente(
  p_codigo text,
  p_mesa text,
  p_nombre_cliente text,
  p_observacion text,
  p_items jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_estado text;
  v_total numeric(10, 2);
  v_items jsonb;
begin
  select estado into v_estado from public.pedidos where codigo = p_codigo for update;
  if v_estado is null then raise exception 'Pedido no encontrado'; end if;
  if v_estado <> 'pendiente' then raise exception 'Solo se puede modificar un pedido pendiente'; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'El pedido debe incluir al menos un producto';
  end if;

  with requested as (
    select
      item->>'producto_id' as producto_id,
      greatest(1, least(50, coalesce((item->>'cantidad')::integer, 1))) as cantidad,
      nullif(trim(item->>'observacion_item'), '') as observacion_item
    from jsonb_array_elements(p_items) item
  ), valid_items as (
    select
      p.id as producto_id,
      p.nombre,
      r.cantidad,
      p.precio as precio_unitario,
      round(p.precio * r.cantidad, 2) as subtotal,
      coalesce(r.observacion_item, '') as observacion_item
    from requested r
    join public.productos p on p.id = r.producto_id
    where p.disponible = true
  )
  select
    coalesce(sum(subtotal), 0),
    coalesce(jsonb_agg(to_jsonb(valid_items)), '[]'::jsonb)
  into v_total, v_items
  from valid_items;

  if jsonb_array_length(v_items) <> jsonb_array_length(p_items) then
    raise exception 'Uno o mas productos no existen o no estan disponibles';
  end if;

  update public.pedidos
  set mesa = trim(p_mesa),
      nombre_cliente = trim(p_nombre_cliente),
      observacion = coalesce(trim(p_observacion), ''),
      total = v_total,
      updated_at = now()
  where codigo = p_codigo;

  delete from public.pedido_items where pedido_codigo = p_codigo;
  insert into public.pedido_items (
    pedido_codigo, producto_id, nombre, cantidad, precio_unitario, subtotal, observacion_item
  )
  select
    p_codigo,
    item->>'producto_id',
    item->>'nombre',
    (item->>'cantidad')::integer,
    (item->>'precio_unitario')::numeric,
    (item->>'subtotal')::numeric,
    item->>'observacion_item'
  from jsonb_array_elements(v_items) item;

  insert into public.historial_estados (pedido_codigo, estado, observacion)
  values (p_codigo, 'pendiente', 'Pedido modificado por el comensal');

  return public.consultar_pedido_publico(p_codigo);
end;
$$;

create or replace function public.cambiar_estado_pedido(p_codigo text, p_nuevo_estado text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_estado text;
  v_rol text;
  v_permitido boolean := false;
begin
  v_rol := public.current_user_role();
  select estado into v_estado from public.pedidos where codigo = p_codigo for update;
  if v_estado is null then raise exception 'Pedido no encontrado'; end if;

  v_permitido :=
    (v_rol = 'caja' and v_estado = 'pendiente' and p_nuevo_estado = 'recibido') or
    (v_rol = 'cocinero' and v_estado = 'recibido' and p_nuevo_estado = 'en_preparacion') or
    (v_rol = 'cocinero' and v_estado = 'en_preparacion' and p_nuevo_estado = 'listo') or
    (v_rol = 'mesera' and v_estado = 'listo' and p_nuevo_estado = 'entregado');

  if not v_permitido then
    raise exception 'Transicion % -> % no autorizada para el rol %', v_estado, p_nuevo_estado, coalesce(v_rol, 'sin rol');
  end if;

  update public.pedidos
  set estado = p_nuevo_estado, estado_id = p_nuevo_estado, updated_at = now()
  where codigo = p_codigo;
  return public.consultar_pedido_publico(p_codigo);
end;
$$;

create or replace function public.registrar_pago_pedido(p_codigo text, p_metodo_pago text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_pedido public.pedidos%rowtype;
begin
  if public.current_user_role() <> 'caja' then raise exception 'Solo Caja puede registrar pagos'; end if;
  if p_metodo_pago not in ('efectivo', 'tarjeta', 'transferencia') then raise exception 'Metodo de pago no valido'; end if;

  select * into v_pedido from public.pedidos where codigo = p_codigo for update;
  if v_pedido.codigo is null then raise exception 'Pedido no encontrado'; end if;
  if v_pedido.estado <> 'entregado' then raise exception 'El pedido debe estar entregado antes de cobrar'; end if;
  if v_pedido.pago_confirmado then raise exception 'El pedido ya fue pagado'; end if;

  update public.pedidos
  set estado = 'cerrado',
      estado_id = 'cerrado',
      estado_pago = 'pagado',
      pago_confirmado = true,
      fecha_confirmacion_pago = now(),
      usuario_caja_id = auth.uid(),
      metodo_pago = p_metodo_pago,
      monto_pagado = total,
      updated_at = now()
  where codigo = p_codigo;

  return public.consultar_pedido_publico(p_codigo);
end;
$$;

alter table public.historial_estados enable row level security;

drop policy if exists pedidos_public_insert on public.pedidos;
drop policy if exists pedido_items_public_insert on public.pedido_items;
drop policy if exists pedidos_internal_update on public.pedidos;
drop policy if exists historial_internal_select on public.historial_estados;
create policy historial_internal_select on public.historial_estados
  for select to authenticated using (public.current_user_role() is not null);

drop policy if exists productos_admin_delete on public.productos;
create policy productos_admin_delete on public.productos
  for delete to authenticated using (public.current_user_role() = 'administradora');

grant execute on function public.registrar_pedido_publico(text, text, text, text, jsonb) to anon, authenticated;
grant execute on function public.consultar_pedido_publico(text) to anon, authenticated;
grant execute on function public.modificar_pedido_pendiente(text, text, text, text, jsonb) to anon, authenticated;
grant execute on function public.cambiar_estado_pedido(text, text) to authenticated;
grant execute on function public.registrar_pago_pedido(text, text) to authenticated;
