-- EDValleDigital - esquema Supabase compatible con los JSON actuales.
-- Ejecutar primero en Supabase SQL Editor. No borra tablas ni datos.

create table if not exists public.productos (
  id text primary key,
  nombre text not null,
  categoria text not null default 'Otros',
  subcategoria text,
  descripcion text not null default '',
  precio numeric(10, 2) not null default 0 check (precio >= 0),
  imagen text not null default '/img/platos/placeholder-plato.svg',
  disponible boolean not null default true,
  destacado boolean not null default false,
  etiquetas text[] not null default '{}'::text[],
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pedidos (
  codigo text primary key,
  estado text not null default 'pendiente'
    check (estado in ('pendiente', 'recibido', 'en_preparacion', 'listo', 'cerrado', 'cancelado')),
  fecha_hora timestamptz not null default now(),
  mesa text not null default '',
  nombre_cliente text not null default '',
  observacion text not null default '',
  total numeric(10, 2) not null default 0 check (total >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pedido_items (
  id bigint generated by default as identity primary key,
  pedido_codigo text not null references public.pedidos(codigo) on delete cascade,
  producto_id text references public.productos(id) on update cascade on delete set null,
  nombre text not null,
  cantidad integer not null check (cantidad > 0),
  precio_unitario numeric(10, 2) not null check (precio_unitario >= 0),
  subtotal numeric(10, 2) not null check (subtotal >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.perfiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  nombre text not null,
  rol text not null check (rol in ('administradora', 'caja', 'cocinero', 'mesera')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists productos_categoria_idx on public.productos(categoria);
create index if not exists productos_disponible_idx on public.productos(disponible);
create index if not exists pedidos_estado_idx on public.pedidos(estado);
create index if not exists pedidos_fecha_hora_idx on public.pedidos(fecha_hora desc);
create index if not exists pedido_items_pedido_codigo_idx on public.pedido_items(pedido_codigo);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
begin
  if not exists (select 1 from pg_trigger where tgname = 'productos_set_updated_at') then
    create trigger productos_set_updated_at
    before update on public.productos
    for each row execute function public.set_updated_at();
  end if;

  if not exists (select 1 from pg_trigger where tgname = 'pedidos_set_updated_at') then
    create trigger pedidos_set_updated_at
    before update on public.pedidos
    for each row execute function public.set_updated_at();
  end if;

  if not exists (select 1 from pg_trigger where tgname = 'perfiles_set_updated_at') then
    create trigger perfiles_set_updated_at
    before update on public.perfiles
    for each row execute function public.set_updated_at();
  end if;
end $$;

create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select rol from public.perfiles where id = auth.uid()
$$;

alter table public.productos enable row level security;
alter table public.pedidos enable row level security;
alter table public.pedido_items enable row level security;
alter table public.perfiles enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'productos' and policyname = 'productos_public_select'
  ) then
    create policy productos_public_select
    on public.productos
    for select
    to anon, authenticated
    using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'productos' and policyname = 'productos_admin_insert'
  ) then
    create policy productos_admin_insert
    on public.productos
    for insert
    to authenticated
    with check (public.current_user_role() = 'administradora');
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'productos' and policyname = 'productos_admin_update'
  ) then
    create policy productos_admin_update
    on public.productos
    for update
    to authenticated
    using (public.current_user_role() = 'administradora')
    with check (public.current_user_role() = 'administradora');
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'pedidos' and policyname = 'pedidos_public_insert'
  ) then
    create policy pedidos_public_insert
    on public.pedidos
    for insert
    to anon, authenticated
    with check (estado = 'pendiente');
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'pedido_items' and policyname = 'pedido_items_public_insert'
  ) then
    create policy pedido_items_public_insert
    on public.pedido_items
    for insert
    to anon, authenticated
    with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'pedidos' and policyname = 'pedidos_internal_select'
  ) then
    create policy pedidos_internal_select
    on public.pedidos
    for select
    to authenticated
    using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'pedido_items' and policyname = 'pedido_items_internal_select'
  ) then
    create policy pedido_items_internal_select
    on public.pedido_items
    for select
    to authenticated
    using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'pedidos' and policyname = 'pedidos_internal_update'
  ) then
    create policy pedidos_internal_update
    on public.pedidos
    for update
    to authenticated
    using (true)
    with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'perfiles' and policyname = 'perfiles_own_select'
  ) then
    create policy perfiles_own_select
    on public.perfiles
    for select
    to authenticated
    using (auth.uid() = id);
  end if;
end $$;
